RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_MAXIMUM_BRIGHTNESS = 200
SPLIT_KEYBOARD = yes

# Enable mouse keys
MOUSEKEY_ENABLE = yes

# Enable caps word
CAPS_WORD_ENABLE = yes

# Enable combos
COMBO_ENABLE = yes
